import { Container, Theme, ThemePanel } from "@radix-ui/themes";
import "@radix-ui/themes/styles.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Navbar from "./Navbar";
import "./globals.css";
import Footer from "./Footer";
// const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "USDT WARS",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={`{inter.className} bg-background_primary_website `}>

        <Theme className="" appearance="light" grayColor="gray" panelBackground="solid">
          <Navbar />
          {/* <main className="container m-auto">

        <Theme appearance="light" grayColor="gray" panelBackground="solid">
          <Navbar />
          <main className="container m-auto">

            <Container>{children}</Container>
          </main> */}
          {children}
          {/* <ThemePanel /> */}

          <Footer />
        </Theme>
      </body>
    </html>
  );
}
